[package]
name = "png2aa-web"
version = "0.1.2"
authors = ["Yusuke Sangenya <longinus.eva@gmail.com>"]

[dependencies]
png2aa = "0.1.2"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
